language: python

python:
  - 2.7
  - 3.5

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - make pep8
  - make pyflakes
  - make test
