before_install:
  - "sudo ln -s /usr/lib/i386-linux-gnu/libz.so /usr/lib/"

install: pip install PIL coverage pep8 pyflakes requests

language: python

python:
  - "2.7"
  - "2.6"

script: make pep8 pyflakes test
